import type { CatalogSectionContent } from "./types";

export const CATALOG_SECTION_CONTENT: CatalogSectionContent = {
  title: "Каталог новостроек и жилых комплексов в Санкт-Петербурге",

  tabs: [
    {
      id: "newbuildings",
      label: "Первичка",
      count: 982,
      description:
        "В базе ЦН МЁД более 11 640 новостроек и ЖК, посмотрите, возможно вам что-нибудь приглянется",
      items: [
        {
          id: "yaninskiy-les",
          title: "Янинский лес",
          location: "Проспект Большевиков",
          locationTagColor: "red",
          image: "/images/catalog/catalog-1.png",
          imageAlt: "ЖК Янинский лес",
          flatsLabel: "19 квартир в продаже",
          priceLabel: "от 347 035 за кв. м",
          to: "/catalog/yaninskiy-les",
        },
        {
          id: "lermontovskiy-54",
          title: "Лермонтовский 54",
          location: "Балтийская",
          locationTagColor: "green",
          image: "/images/catalog/catalog-2.png",
          imageAlt: "ЖК Лермонтовский 54",
          flatsLabel: "19 квартир в продаже",
          priceLabel: "от 347 035 за кв. м",
          to: "/catalog/lermontovskiy-54",
        },
        {
          id: "aviator",
          title: "Авиатор",
          location: "Девяткино",
          locationTagColor: "blue",
          image: "/images/catalog/catalog-3.png",
          imageAlt: "ЖК Авиатор",
          flatsLabel: "19 квартир в продаже",
          priceLabel: "от 347 035 за кв. м",
          to: "/catalog/aviator",
          detailsLabel: "Смотреть детали",
        },
        {
          id: "gorod-zvezd",
          title: "Город звезд",
          location: "Обухово",
          locationTagColor: "blue",
          image: "/images/catalog/catalog-4.png",
          imageAlt: "ЖК Город звезд",
          flatsLabel: "340 квартир в продаже",
          priceLabel: "от 164 000 за кв. м",
          to: "/catalog/gorod-zvezd",
        },
        {
          id: "polis-novoselie",
          title: "Полис новоселье вторая строка названия",
          location: "Проспект Ветеранов",
          locationTagColor: "red",
          image: "/images/catalog/catalog-5.png",
          imageAlt: "ЖК Полис новоселье",
          flatsLabel: "19 квартир в продаже",
          priceLabel: "от 347 035 за кв. м",
          to: "/catalog/polis-novoselie",
        },
        {
          id: "univer-city",
          title: "Univer city",
          location: "Купчино",
          locationTagColor: "orange",
          image: "/images/catalog/catalog-6.png",
          imageAlt: "ЖК Univer city",
          flatsLabel: "65 квартир в продаже",
          priceLabel: "от 226 035 за кв. м",
          to: "/catalog/univer-city",
        },
      ],
      mapLink: {
        label: "Посмотреть все объекты на карте",
        to: "/map",
        icon: "pin",
      },
    },
    {
      id: "resale",
      label: "Вторичка",
      count: 1250,
      description: "Подборка объектов вторичного рынка Санкт-Петербурга",
      items: [
        {
          id: "yaninskiy-les",
          title: "Янинский лес",
          location: "Проспект Большевиков",
          locationTagColor: "blue",
          image: "/images/catalog/catalog-1.png",
          imageAlt: "ЖК Янинский лес",
          flatsLabel: "19 квартир в продаже",
          priceLabel: "от 347 035 за кв. м",
          to: "/catalog/yaninskiy-les",
        },
        {
          id: "lermontovskiy-54",
          title: "Лермонтовский 54",
          location: "Балтийская",
          locationTagColor: "blue",
          image: "/images/catalog/catalog-2.png",
          imageAlt: "ЖК Лермонтовский 54",
          flatsLabel: "19 квартир в продаже",
          priceLabel: "от 347 035 за кв. м",
          to: "/catalog/lermontovskiy-54",
        },
        {
          id: "aviator",
          title: "Авиатор",
          location: "Девяткино",
          locationTagColor: "orange",
          image: "/images/catalog/catalog-3.png",
          imageAlt: "ЖК Авиатор",
          flatsLabel: "19 квартир в продаже",
          priceLabel: "от 347 035 за кв. м",
          to: "/catalog/aviator",
          detailsLabel: "Смотреть детали",
        },
      ],
      mapLink: {
        label: "Посмотреть все объекты на карте",
        to: "/map",
        icon: "pin",
      },
    },
    {
      id: "commercial",
      label: "Коммерция",
      count: 120,
      description: "Коммерческие помещения и объекты для бизнеса",
      items: [
        {
          id: "yaninskiy-les",
          title: "Янинский лес",
          location: "Проспект Большевиков",
          locationTagColor: "red",
          image: "/images/catalog/catalog-1.png",
          imageAlt: "ЖК Янинский лес",
          flatsLabel: "19 квартир в продаже",
          priceLabel: "от 347 035 за кв. м",
          to: "/catalog/yaninskiy-les",
        },
        {
          id: "lermontovskiy-54",
          title: "Лермонтовский 54",
          location: "Балтийская",
          locationTagColor: "green",
          image: "/images/catalog/catalog-2.png",
          imageAlt: "ЖК Лермонтовский 54",
          flatsLabel: "19 квартир в продаже",
          priceLabel: "от 347 035 за кв. м",
          to: "/catalog/lermontovskiy-54",
        },
        {
          id: "aviator",
          title: "Авиатор",
          location: "Девяткино",
          locationTagColor: "blue",
          image: "/images/catalog/catalog-3.png",
          imageAlt: "ЖК Авиатор",
          flatsLabel: "19 квартир в продаже",
          priceLabel: "от 347 035 за кв. м",
          to: "/catalog/aviator",
          detailsLabel: "Смотреть детали",
        },
      ],
      mapLink: {
        label: "Посмотреть все объекты на карте",
        to: "/map",
        icon: "pin",
      },
    },
  ],

  promo: {
    lead: "Хотите посмотреть",
    title: "больше объектов?",
    buttonLabel: "Смотреть весь каталог",
    buttonTo: "/catalog",
    image: "/images/catalog/catalog-promo.png",
    imageAlt: "Каталог недвижимости",
  },
};
