import type { SocialsSectionContent } from "./types";

export const SOCIALS_SECTION_CONTENT: SocialsSectionContent = {
  title: "Смотрите\nи\u00A0читайте нас\nв\u00A0соцсетях",
  description:
    "Говорим простым и понятным языком о недвижимости, подписывайтесь!",

  channels: [
    [
      {
        id: "tiktok",
        variant: "channel",
        href: "/",
        icon: "social-tiktok",
        label: "Мы в TikTok",
        followers: "93 500",
      },
      {
        id: "vk",
        variant: "channel",
        href: "/",
        icon: "social-vk",
        label: "Мы ВКонтакте",
        followers: "3 150",
      },
      {
        id: "instagram",
        variant: "channel",
        href: "/",
        icon: "social-instagram",
        label: "Наш Instagram",
        followers: "93 500",
      },
    ],
    [
      {
        id: "telegram",
        variant: "channel",
        href: "/",
        icon: "social-telegram",
        label: "Наш Telegram",
        followers: "21 345",
      },
      {
        id: "dzen",
        variant: "channel",
        href: "/",
        icon: "social-dzen",
        label: "Мы в Дзене",
        followers: "93 500",
      },
      {
        id: "youtube",
        variant: "channel",
        href: "/",
        icon: "social-youtube",
        label: "Мы на Ютьюб",
        followers: "21 345",
      },
    ],
  ],

  posts: [
    {
      id: "post-1",
      variant: "post",
      size: "sm",
      href: "/",
      icon: "social-instagram",
      title: "Не берите эту рассрочку",
      imageSrc: "/images/socials/social-1.png",
      imageAlt: "Пост из Instagram про рассрочку",
      views: "1 234",
    },
    {
      id: "post-2",
      variant: "post",
      size: "lg",
      href: "/",
      icon: "social-telegram",
      title: "Ставка 0,11% на Балтийской",
      imageSrc: "/images/socials/social-2.png",
      imageAlt: "Пост про ставку 0,11% на Балтийской",
      views: "1 234",
    },
    {
      id: "post-3",
      variant: "post",
      size: "sm",
      href: "/",
      icon: "social-instagram",
      title: "Ипотека vs рассрочка",
      imageSrc: "/images/socials/social-3.png",
      imageAlt: "Пост про ипотеку и рассрочку",
      views: "4 875",
    },
    {
      id: "post-4",
      variant: "post",
      size: "sm",
      href: "/",
      icon: "social-instagram",
      title: "Где живут знаменитости в Петербурге",
      imageSrc: "/images/socials/social-4.png",
      imageAlt: "Пост про знаменитостей в Петербурге",
      views: "4 795",
    },
    {
      id: "post-5",
      variant: "post",
      size: "sm",
      href: "/",
      icon: "social-tiktok",
      title: "Ключи получили — деньги потеряли",
      imageSrc: "/images/socials/social-5.png",
      imageAlt: "Пост про получение ключей",
      views: "3 900",
    },
  ],
};
